name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"  # Only run on tags that look like "v1.2.3"

permissions:
  contents: read  # Read access to the repository
  packages: write   # Write access to the GitHub Container Registry

jobs:

  build:
    runs-on: ubuntu-latest   # Use the latest version of Ubuntu

    steps:
      - name: Set up QEMU   # Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx  # Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Checkout repository
        uses: actions/checkout@v4
        depth: 1  # Only fetch the most recent commit

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

      - name: Build and push Docker image with latest tag
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,macos/arm64
          file: ./Dockerfile
          push: false  # Make True, if you want to push the image
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
